name: subfolder
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # first, install dependencies and Cypress
      # from the root folder using the lock file
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # now run the tests from the subfolder
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: packages/e2e
          start: yarn start-server
